### ISSUE TITLE
我看到晚的 commint 是在一年多以前，我想要翻译完所有的文章

### ISSUE THREAD

**Issue by shenlebantongying** [lzwjava/paul-graham-essays-cn#2]
如题，
我还想做一个静态的小网站来储存

**Comment by jzcxer** [comment]
换句话说，我已经接管了这个项目

**Comment by jzcxer** [comment]
使用 google translate toolkit 来作为工具，翻译完再上传

**Comment by shenlebantongying** [comment]
我在这里不能直接做更改，所以直接 Fork 了项目到我的仓库里面了。

**Comment by EECSGEEK** [comment]
@jzcxer 翻译的难度和工作量都有点大
静态网页存储的话感觉还行，我觉得谷歌硬盘保存也可以，但是我不知道谷歌硬盘能不能增量同步文件，
Dropbox是可以同步文件。
